---
title: "Filename Quality"
author: "Alvin, Lin"
date: "`r Sys.Date()`"
format:
   html:
     theme: flatly
     self-contained: true
toc: true
toc-depth: 3
toc-location: left
execute:
  echo: false
  warning: false 
  keep-md: true
---
<!-- Instructions -->
<!-- Step 1 : Copy the directory of upload -->
<!-- Step 2 : Ctrl + Alt + R -->
<!-- Step 3 : And then paste -->

<!-- Case 1: Condition ID -->
<!-- \\oneabbott.com\dept\ADC\Technical_OPS\Clinical_Affairs\CDM_23238\003 -->

<!-- Case 2: Subject ID and Condition ID -->
<!-- \\wf00168p.oneabbott.com\data1\CDM\ADC-US-RES-23241\SE01\UploadData\UUU\UUU_Datafiles\083-IDR\2023-12-01_1554 -->

<!-- Case 3: Duplicated uploads and Put files on the wrong folders -->
<!-- \\wf00168p.oneabbott.com\data1\CDM\ADC-US-RES-22225\SE13_Ket\UploadData\UUU\UUU_DataFiles\SDRI-058 -->

<!-- Case 4: Folder name and Folder structure -->
<!-- \\wf00168p.oneabbott.com\data1\CDM\ADC-US-RES-21210\UploadData\AUU\AUU_DataFiles -->


<!-- Upload Data has a blank  -->
<!-- \\wf00168p.oneabbott.com\data1\CDM\ADC-US-RES-22225\SE29_Ket\Upload Data\UUU\UUU_DataFiles\ERA-117 -->
<!-- Data Files has a blank and Multiple Visits and rounds-->
<!-- \\wf00168p.oneabbott.com\data1\CDM\ADC-US-RES-22225\SE36_Lac\UploadData\UUU\UUU Data Files -->


<!-- External -->
<!-- UUU \\wf00168p.oneabbott.com\data1\CDM\ALB-US-EXP-21001\UploadData\AUU\AUU_DataFiles -->
<!-- \\wf00168p.oneabbott.com\data1\CDM\ADC-US-RES-23241\SE01\UploadData\UUU\UUU_Datafiles\083-IDR\2023-12-01_1554 -->

<!-- Upload Data has a blank  -->
<!-- \\wf00168p.oneabbott.com\data1\CDM\ADC-US-RES-22225\SE29_Ket\Upload Data\UUU\UUU_DataFiles\ERA-117 -->
<!-- Data Files has a blank and Multiple Visits and rounds-->
<!-- \\wf00168p.oneabbott.com\data1\CDM\ADC-US-RES-22225\SE36_Lac\UploadData\UUU\UUU Data Files -->
<!-- Multiple Visits and rounds -->
<!-- UUU/UUU_DataFiles/SDRI-058/000580001/FV/Apol0580001_______CAP_230405_101208/Apol0580001_______CAP_230405_101208_events.csv -->

<!-- InHouse -->
<!-- Round 1 -->
<!-- \\oneabbott.com\dept\ADC\Technical_OPS\Clinical_Affairs\CDM_23238\003 -->
<!-- \\oneabbott.com\dept\ADC\Technical_OPS\Clinical_Affairs\CDM_23238\004 -->
<!-- \\oneabbott.com\dept\ADC\Technical_OPS\Clinical_Affairs\CDM_23238\007 -->

```{r}
#| label: User-defined path
path <- readline("Please paste the directory: ")
```

```{r}
#| label: Libaray Packages 
#| message: false
library(tidyverse)
library(openxlsx)
library(fs)
```

```{r}
#| label: Directory
file_list <- dir_ls(gsub("\\\\", "/", path),recurse = T,glob = "*extracted_realm.zip|*events.csv|*readings.csv")
```
 <!-- & str_detect(file_list,regex("AUU_DataFiles|UUU_DataFiles|UUU Data Files",ignore_case = T)) -->
```{r}
#| label: Filter Path
if (any(str_detect(file_list,"CDM_23238"))){
file_path <- file_list[!str_detect(file_list,regex("Transfers|Transfer|Archive|Archives",ignore_case = T))]} else {
file_path <- file_list[!str_detect(file_list,regex("Transfers|Transfer|Archive|Archives|Final",ignore_case = T))]}
```

```{r}
#| label: Wrangle Path
if (any(str_detect(file_list,"CDM_23238"))){
  data <- tibble(Path = str_extract(str_remove_all(file_path,"[:blank:]"),regex("(?<=Clinical_Affairs/).+|(?<=Upload Data/).+")),
       Site  = str_extract(Path,regex("(?<=/Apol)[:upper:]{3}|(?<=/Mobi)[:upper:]{3}|(?<=/[:alnum:]{2}_)[:upper:]{3}")),
                `Subject ID` = str_extract(Path,regex("(?<=/ApolADC)[:digit:]{4}|(?<=/MobiADC)[:digit:]{4}|(?<=/[:alnum:]{2}_ADC)[:digit:]{4}")),
                `Condition ID` = str_extract(Path,regex("(?<=ApolADC[:digit:]{10}_)[:alnum:]+|(?<=MobiADC[:digit:]{10}_)[:alnum:]+|(?<=[:alnum:]{2}_ADC[:digit:]{4}_)[:alnum:]+")),
            Date = ymd(str_extract(Path,regex("(?<=_)[:digit:]{6}"))),
            Time = hms::as_hms(str_c(
              str_extract(Path,regex("(?<=_[:digit:]{6}_)[:digit:]{2}")),
              str_extract(Path,regex("(?<=_[:digit:]{6}_[:digit:]{2})[:digit:]{2}")),
              str_extract(Path,regex("(?<=_[:digit:]{6}_[:digit:]{4})[:digit:]{2}")),sep = ":")),
            Type = str_extract(Path,"AUU|UUU|GKS"),
            Visit = str_extract(Path,regex("FV|V3|V4|V5|Visit3|Visit4|Visit5|Visit_3|Visit_4|Visit_5|C1|C2|C3|C4|Exit|Round1|Round2",ignore_case = T))
       ) |> 
          distinct(pick(c(Site:Time)),.keep_all = T) |> 
          mutate(Count = n(),.by = c(Type,`Subject ID`,`Condition ID`,Visit)) |>
          mutate(Status = case_when(
               str_length(`Subject ID`) != median(str_length(`Subject ID`),na.rm = T) ~ "No Good: Please Check Subject ID",
               str_length(`Condition ID`) != 3 |
               str_detect(`Condition ID`,"[:lower:]") |
               str_detect(`Condition ID`,"[:digit:]{3}") ~ "No Good: Please Check Condition ID",
               is.na(`Subject ID`) | is.na(`Condition ID`) ~ "No Good: Please Check Subject ID and Condition ID",
               str_extract(Site,"[:digit:]{3}") != str_sub(`Subject ID`,1,3) ~ "No Good: Put files on the wrong Site folders",
               Count != 1 ~ "No Good: Duplicated Uploads",
               .default = "Good")) |> 
         arrange(`Subject ID`)
} else {
data <- tibble(Path = str_extract(str_remove_all(file_path,"[:blank:]"),regex("(?<=UploadData/).+")),
               Site  = str_c(str_extract(Path,regex("(?<=DataFiles/)[:alnum:]+",ignore_case = T)),
                     str_extract(Path,regex("(?<=DataFiles/[:alnum:]{3,4}[:punct:]{1})[:alnum:]+",ignore_case = T)),
                     sep = "-"),
              `Subject ID` = str_extract(Path,regex("(?<=/Mobi)[:digit:]+|(?<=/Atna)[:digit:]+|(?<=/Apol)[:digit:]+")),
              `Condition ID` = str_extract(Path,regex("(?<=[:punct:]{7})[:alnum:]+")),
            Date = ymd(str_extract(Path,regex("(?<=_)[:digit:]{6}"))),
            Time = hms::as_hms(str_c(
              str_extract(Path,regex("(?<=_[:digit:]{6}_)[:digit:]{2}")),
              str_extract(Path,regex("(?<=_[:digit:]{6}_[:digit:]{2})[:digit:]{2}")),
              str_extract(Path,regex("(?<=_[:digit:]{6}_[:digit:]{4})[:digit:]{2}")),sep = ":")),
            Type = str_extract(Path,"[:alpha:]+"),
            Visit = str_extract(Path,regex("FV|V3|V4|V5|Visit3|Visit4|Visit5|Visit_3|Visit_4|Visit_5|C1|C2|C3|C4|Exit",ignore_case = T))) |>
          # Remove dualsensors_events.csv and dualsensors_extracted_realm.zip
           distinct(pick(c(Site:Time)),.keep_all = T) |> 
          mutate(Count = n(),.by = c(Type,`Subject ID`,`Condition ID`,Visit)) |>
          mutate(Status = case_when(
               str_length(`Subject ID`) != median(str_length(`Subject ID`),na.rm = T) ~ "No Good: Please Check Subject ID",
               str_length(`Condition ID`) != 3 |
               str_detect(`Condition ID`,"[:lower:]") |
               str_detect(`Condition ID`,"[:digit:]{3}") ~ "No Good: Please Check Condition ID",
               is.na(`Subject ID`) | is.na(`Condition ID`) ~ "No Good: Please Check Subject ID and Condition ID",
               str_extract(Site,"[:digit:]{3}") != str_sub(`Subject ID`,1,3) ~ "No Good: Put files on the wrong Site folders",
               Count != 1 ~ "No Good: Duplicated Uploads",
               .default = "Good")) |> 
         arrange(`Subject ID`)
}
```

```{r}
#| label: Output excel
# Create a workbook
wb <- createWorkbook()
# Create style 
style1 <- createStyle(fontColour = "coral") 
# Add a empty worksheet
addWorksheet(wb,"Filename-Quality")
# Write the data to the worksheet
writeData(wb,"Filename-Quality", data, startCol = 1, startRow = 1, rowNames = F)
# Conditional Formatting
conditionalFormatting(wb, "Filename-Quality", cols = 10, rows = 1:(nrow(data) + 1), style = style1, type = "contains", rule = "No Good")
# Create file name
if (any(str_detect(file_list,"CDM_23238"))) {
file_name <- str_c(str_replace(str_extract(file_path[1],regex("(?<=CDM_).{9}")),"/","-Sub")," Filename-Quality.xlsx")
} else {
file_name = str_c(str_replace(str_remove(str_extract(file_path[1],regex("(?<=CDM/)[:graph:]+|(?<=M:/)[:graph:]+")),regex("/UploadData.+|/Upload")),"/","-"), " Filename-Quality.xlsx")}
# Save worksheet
saveWorkbook(wb, file_name, overwrite = TRUE)
```
